/**
 * AUTO-GENERATED by scripts/sync-wode-branded-models.mjs — do not edit by hand.
 * Source: shared-components/config/wodeBrandedModels.ts
 */
/** 内置中转站模型目录 */
export const WODE_BRANDED_MODELS = [
    {
        "id": "wode/doubao-pro",
        "shortNames": [
            "wode-doubao-pro",
            "wode-doubao-seed-2-1-pro",
            "wode-doubao"
        ],
        "label": "豆包 Seed 2.1 Pro",
        "subtitle": "字节 · 旗舰 · 多模态",
        "upstreamId": "bytedance/doubao-seed-2-1-pro",
        "tier": "high",
        "capabilities": [
            "chat",
            "vision"
        ],
        "mediaInput": {
            "image": "native",
            "video": "native",
            "pdf": "native",
            "office": "extract",
            "remoteImageUrl": true
        },
        "region": "china"
    },
    {
        "id": "wode/doubao-turbo",
        "shortNames": [
            "wode-doubao-turbo",
            "wode-doubao-seed-2-1-turbo"
        ],
        "label": "豆包 Seed 2.1 Turbo",
        "subtitle": "字节 · 高吞吐 · 多模态",
        "upstreamId": "bytedance/doubao-seed-2-1-turbo",
        "tier": "mid",
        "capabilities": [
            "chat",
            "vision"
        ],
        "mediaInput": {
            "image": "native",
            "video": "native",
            "pdf": "native",
            "office": "extract",
            "remoteImageUrl": true
        },
        "region": "china"
    },
    {
        "id": "wode/deepseek-v4-pro",
        "shortNames": [
            "wode-deepseek-v4-pro",
            "wode-deepseek-pro",
            "wode-deepseek"
        ],
        "label": "Wode DeepSeek V4 Pro",
        "subtitle": "深度推理",
        "upstreamId": "deepseek/deepseek-v4-pro",
        "tier": "high",
        "capabilities": [
            "chat"
        ],
        "region": "china"
    },
    {
        "id": "wode/deepseek-v4-flash",
        "shortNames": [
            "wode-deepseek-v4-flash",
            "wode-deepseek-flash"
        ],
        "label": "Wode DeepSeek V4 Flash",
        "subtitle": "快速对话",
        "upstreamId": "deepseek/deepseek-v4-flash",
        "tier": "low",
        "capabilities": [
            "chat"
        ],
        "region": "china"
    },
    {
        "id": "wode/qwen3.8-max",
        "shortNames": [
            "wode-qwen3.8-max",
            "wode-qwen"
        ],
        "label": "通义千问 3.8 Max",
        "subtitle": "阿里 · 多模态 · 长上下文",
        "upstreamId": "qwen3.8-max",
        "tier": "high",
        "capabilities": [
            "chat",
            "vision"
        ],
        "mediaInput": {
            "image": "native",
            "video": "native",
            "pdf": "native",
            "office": "extract",
            "remoteImageUrl": true
        },
        "region": "china"
    },
    {
        "id": "wode/minimax-m3",
        "shortNames": [
            "wode-minimax-m3",
            "wode-minimax"
        ],
        "label": "MiniMax M3",
        "subtitle": "MiniMax · 多模态 · Agent",
        "upstreamId": "minimax/MiniMax-M3",
        "tier": "high",
        "capabilities": [
            "chat",
            "vision"
        ],
        "mediaInput": {
            "image": "native",
            "video": "native",
            "pdf": "file_api",
            "office": "file_api",
            "remoteImageUrl": true
        },
        "region": "china"
    },
    {
        "id": "wode/kimi-k3",
        "shortNames": [
            "wode-kimi-k3",
            "wode-kimi"
        ],
        "label": "Kimi K3",
        "subtitle": "Moonshot · 旗舰 · 1M 上下文",
        "upstreamId": "moonshotai/kimi-k3",
        "tier": "high",
        "capabilities": [
            "chat",
            "vision"
        ],
        "mediaInput": {
            "image": "native",
            "video": "native",
            "pdf": "file_api",
            "office": "file_api",
            "remoteImageUrl": false
        },
        "contextWindow": 1048576,
        "region": "china"
    },
    {
        "id": "wode/kimi-code-k3",
        "shortNames": [
            "wode-kimi-code-k3",
            "wode-kimi-code",
            "kimi-code-k3"
        ],
        "label": "Kimi Code K3",
        "subtitle": "Kimi Code · 1M 上下文 · 图/视频",
        "upstreamId": "kimicode/k3",
        "tier": "high",
        "capabilities": [
            "chat",
            "vision"
        ],
        "mediaInput": {
            "image": "native",
            "video": "native",
            "pdf": "extract",
            "office": "extract",
            "remoteImageUrl": false
        },
        "contextWindow": 1048576,
        "region": "china"
    },
    {
        "id": "wode/kimi-code-k3-256k",
        "shortNames": [
            "wode-kimi-code-k3-256k"
        ],
        "label": "Kimi Code K3 256K",
        "subtitle": "Kimi Code · 256K · 图（无视频）",
        "upstreamId": "kimicode/k3-256k",
        "tier": "high",
        "capabilities": [
            "chat",
            "vision"
        ],
        "mediaInput": {
            "image": "native",
            "video": "unsupported",
            "pdf": "extract",
            "office": "extract",
            "remoteImageUrl": false
        },
        "contextWindow": 262144,
        "region": "china"
    },
    {
        "id": "wode/glm-5.2",
        "shortNames": [
            "wode-glm-5.2",
            "wode-glm"
        ],
        "label": "GLM 5.2",
        "subtitle": "Z.ai · 长上下文 · 代码",
        "upstreamId": "z-ai/glm-5.2",
        "tier": "high",
        "capabilities": [
            "chat"
        ],
        "region": "china"
    }
];

const WODE_LEGACY_MODEL_REDIRECTS = {
};

export const WODE_BRANDED_ID_SET = new Set(WODE_BRANDED_MODELS.map(m => m.id));

export const WODE_SHORT_NAME_MAP = Object.fromEntries(
  WODE_BRANDED_MODELS.flatMap(m => m.shortNames.map(s => [s, m.id])),
);

const WODE_UPSTREAM_ID_MAP = Object.fromEntries(
  WODE_BRANDED_MODELS.map(model => [model.upstreamId.toLowerCase(), model.id]),
);

export function buildWodeApiModelMap() {
  return Object.fromEntries(
    WODE_BRANDED_MODELS.map((model) => [
      model.id,
      {
        key: model.id,
        name: model.label,
        subtitle: model.subtitle,
        region: model.region,
      },
    ]),
  );
}

export function isWodeBrandedModel(id) {
  if (!id) return false;
  if (WODE_BRANDED_ID_SET.has(id)) return true;
  if (WODE_SHORT_NAME_MAP[id]) return true;
  if (WODE_UPSTREAM_ID_MAP[id.toLowerCase()]) return true;
  return Boolean(WODE_LEGACY_MODEL_REDIRECTS[id]);
}

export function resolveWodeBrandedId(nameOrId) {
  if (!nameOrId) return undefined;
  const legacy = WODE_LEGACY_MODEL_REDIRECTS[nameOrId];
  if (legacy) return legacy;
  if (WODE_BRANDED_ID_SET.has(nameOrId)) return nameOrId;
  return WODE_SHORT_NAME_MAP[nameOrId] ?? WODE_UPSTREAM_ID_MAP[nameOrId.toLowerCase()];
}

export function resolveWodeUpstreamId(wodeId) {
  const resolved = resolveWodeBrandedId(wodeId) ?? wodeId;
  const entry = WODE_BRANDED_MODELS.find(m => m.id === resolved);
  return entry?.upstreamId;
}

export function getWodeBrandedById(id) {
  const resolved = resolveWodeBrandedId(id) ?? id;
  return WODE_BRANDED_MODELS.find(m => m.id === resolved);
}

export function getWodeBrandedSubtitle(opencodeKey) {
  const entry = WODE_BRANDED_MODELS.find((model) => model.shortNames.includes(opencodeKey));
  return entry?.subtitle;
}
